name: sunshine
description: Sunshine DAO frontend
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  path_provider: ^1.6.5
  flutter_screenutil: ^2.2.0
  injectable: ^0.4.0+1
  websafe_svg: ^1.1.0
  get_it: ^4.0.2
  shared_preferences: ">=0.5.0 <2.0.0"
  intl: ^0.16.1
  auto_route: ^0.6.0
  url_launcher: ^5.5.0
  http: ^0.12.2
  http_extensions: ^0.1.2
  http_extensions_cache: ^0.1.3
  shimmer: ^1.1.1
  sunshine_ffi:
    path: ./packages/sunshine
  timeago:
    path: ./packages/timeago

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.6.0
  build_runner: ^1.9.0
  flutter_launcher_icons: "^0.7.5"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/chainspec.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
