on: [push, pull_request]

name: Android

jobs:
  ci:
    name: Compile, Build and Release
    runs-on: macos-latest
    steps:
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm/10.0
          key: ${{ runner.os }}-cached-llvm-10.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm/10.0
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Install WASM Target
        run: rustup target add wasm32-unknown-unknown

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target/aarch64-linux-android
            target/armv7-linux-androideabi
            target/x86_64-linux-android
            target/i686-linux-android
            target/aarch64-apple-ios
            target/x86_64-apple-ios
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Cargo Tools (cargo-make)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: install
          args: cargo-make

      - name: Install Cargo Tools (cbindgen, v0.14.4)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: install
          args: cbindgen --version 0.14.4

      - name: Install Cargo Tools (dart-bindgen)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: install
          args: dart-bindgen --features cli

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Run Flutter pub get
        run: flutter pub get

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v1

      - name: Cache NDK
        id: cache-ndk
        uses: actions/cache@v2
        with:
          path: /Users/runner/android/ndk-bundle
          key: ${{ runner.os }}-cached-ndk

      - name: Install Android NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: $ANDROID_SDK_ROOT/tools/bin/sdkmanager ndk-bundle

      - name: Set Android NDK Env
        run: echo '::set-env name=ANDROID_NDK_HOME::/Users/runner/android/ndk-bundle'

      - name: Install Android Targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

      - name: Create Release (Android)
        id: create_release
        uses: ChanTsune/release-with-commit@v1.0.0
        with:
          regexp: "Release (\\d+([.]\\d+)*)\n*((\\s|\\S)+)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "v$1"
          body: "$3"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo make android (Debug)
        if: steps.create_release.outputs.upload_url == null
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: android-dev

      - name: Build APK (x86_64, Debug)
        if: steps.create_release.outputs.upload_url == null
        run: flutter build apk --debug

      - name: Run Tests (Android Emulator)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86_64
          working-directory: ./android
          script: ./gradlew connectedCheck

      - name: Run cargo make android (Release)
        if: steps.create_release.outputs.upload_url != null
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: android-arm --profile release

      - name: Build APK (arm64, Release)
        if: steps.create_release.outputs.upload_url == null
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload Release (Android)
        id: upload-release-asset
        if: steps.create_release.outputs.upload_url != null
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: sunshine-release-arm64.apk
          asset_content_type: application/octet-stream
